version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: storyteller
      POSTGRES_PASSWORD: storyteller123
      POSTGRES_DB: storyteller
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - story-network

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://storyteller:storyteller123@db:5432/storyteller
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: >
      sh -c "sleep 10 && python /app/app/setup.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - story-network

volumes:
  postgres_data:

networks:
  story-network:
    driver: bridge
